import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://vpshrfqnnwdtkzgokddo.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwc2hyZnFubndkdGt6Z29rZGRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzkyMzk1MjIsImV4cCI6MTk5NDgxNTUyMn0.rKAIh0RCKsmLzMlSPlnDSm3qgA04vy066NeZ_rMWSr4')